// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import localFont from "next/font/local";
// import Link from "next/link";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <header className="bg-gray-800 text-white p-4">
//           <nav className="container mx-auto flex justify-between">
//             <Link href="/" className="text-lg font-bold">
//               Home
//             </Link>
//             <Link href="/about" className="text-lg font-bold">
//               About
//             </Link>
//           </nav>
//         </header>

//         <main className="container mx-auto p-5">
//           {children}
//         </main>

//         <footer className="text-center p-4 bg-gray-800 text-white">
//           <p>&copy; {new Date().getFullYear()} Create Next App. All rights reserved.</p>
//         </footer>
//       </body>
//     </html>
//   );
// }


// app/layout.js
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";
import Header from "./components/Header";  // Import the Header
import Footer from "./components/Footer";  // Import the Footer

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header /> {/* Header added here */}
        <main className="flex-grow">{children}</main> {/* Ensures content grows */}
        <Footer /> {/* Footer added here */}
      </body>
    </html>
  );
}
